# ============================================================
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# 
#                        WARNING!
# This program is wholly generated by artificial intelligence. 
# While I have done as much as I can to fix errors and 
# anything of the sort, you are still running this program at 
# your own risk.
# Additionally, you may come across some nasty stuff. This is
# taking images from Gelbooru, and while I have filtered out
# the stuff that most people will object to (line 113 if you
# want to change it), there will be stuff that slips through
# the cracks. 
# Remember, every image displayed is downloaded through your 
# ISP, and stays on your computer until you delete it MANUALLY.
# You can find the images in the "cache" folder,
# placed in whichever directory you run this program in.
# Basically,
#                           BE  SAFE
#                        STAY PROTECTED
#                           HAVE FUN
# 
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# ============================================================

# ============================================================
# SETUP
# ============================================================
# 
# 1. Go to Gelbooru
# 2. Make an account
# 3. Go to options
# 4. Go to "API Access Credentials"
# 5. Copy over your API Access Key to line 84
# and User ID to line 85
# The string should be formatted like this:
# &api_key=[API_KEY]&user_id=[USER_ID]
# with no square brackets around it
# 6. (optional) Edit any preferences in the configuration section
# I recommend changing max image size (line 118)
# 7. (optional) Edit blacklist options, but heed the warning!
# 8. Run the program

# ============================================================
# CONTROLS
# ============================================================
# 
# | Key     | Action                     |
# | ------- | -------------------------- |
# | ← / →   | Previous / Next image      |
# | Space   | Next image                 |
# | R       | Toggle auto-scroll         |
# | + / =   | Increase auto-scroll delay |
# | -       | Decrease auto-scroll delay |
# | Tab     | Toggle overlay             |
# | F       | Toggle fade transitions    |
# | Esc / Q | Quit                       |

import io
import os
import sys
import time
import queue
import random
import hashlib
import threading

import pyperclip

import pygame
import requests

from pathlib import Path
from PIL import Image

# ============================================================
# CONFIGURATION
# ============================================================

# Your user ID and API key are in your account options in Gelbooru
# It is under API Access Credentials, and it is formatted like so:
# &api_key=[API_KEY]&user_id=[USER_ID]
# Without the square brackets around it
API_KEY = "REPLACE_WITH_API_KEY"
USER_ID = "REPLACE_WITH_USER_ID"

# Default cache folder path
CACHE_FOLDER = Path("cache")

CACHE_FOLDER.mkdir(exist_ok=True)

# Editable in program - change for a new default value
AUTO_SCROLL_SECONDS = 3

# Change for more or less images preloaded ahead of the current
PRELOAD_COUNT = 15

# Change for a faster or slower fade
FADE_SPEED = 400          # milliseconds

# Editable in program - change for a new default value
SHOW_OVERLAY = True

# Editable in program - change for a new default value
ENABLE_FADE = False

# Background colour in RGB
BACKGROUND = (0,0,0)

# Some basic exclusions, space is required before the first tag
# Anything animated is excluded to get better results as videos are unable to be played
# GIFs can be played, but its only the first frame of them so there isn't much point
EXCLUDED_TAGS = " -animated -video -animated_gif -loli -shota -pee -peeing -vomit -poop"

# Images larger than this are resized before being stored in RAM
# Change it to the resolution of your monitor to get the best resolution

MAX_IMAGE_SIZE = (1920,1080)

# Swap comments of the extensions if you want to include GIFs
# Remember that it's only the first frame of the animation!
SUPPORTED_EXTENSIONS = (
    ".jpg",
    ".jpeg",
    ".png",
#    ".gif",
)

UNSUPPORTED_EXTENSIONS = (
    ".webm",
    ".mp4",
    ".swf",
    ".gif",
)

# ============================================================
# HTTP SESSION
# ============================================================

session = requests.Session()

session.headers.update({

    "User-Agent":

        "Mozilla/5.0 "

        "(Windows NT 10.0; Win64; x64) "

        "AppleWebKit/537.36 "

        "(KHTML, like Gecko) "

        "Chrome/137 Safari/537.36",

    "Referer":

        "https://gelbooru.com/",

})

# ============================================================
# STARTUP MENU
# ============================================================

def startup_menu():

    pygame.init()

    WIDTH = 900
    HEIGHT = 650

    screen = pygame.display.set_mode((WIDTH, HEIGHT))

    pygame.display.set_caption("Gelbooru Viewer")

    clock = pygame.time.Clock()

    title_font = pygame.font.SysFont("Segoe UI", 42, bold=True)
    label_font = pygame.font.SysFont("Segoe UI", 24)
    text_font = pygame.font.SysFont("Consolas", 24)

    settings = {

        "tags":"",

        "limit":"100",

        "randomize":True,

        "sortscore":True

    }

    active = "tags"

    cursor = {

        "tags": len(settings["tags"]),

        "limit": len(settings["limit"])

    }

    active = "tags"

    # ---------------- Rectangles ----------------

    tag_box = pygame.Rect(60,120,780,45)

    limit_box = pygame.Rect(60,220,200,45)

    start_button = pygame.Rect(280,560,340,55)

    checkboxes = {

        "randomize":pygame.Rect(60,330,22,22),

        "sortscore":pygame.Rect(60,370,22,22),

    }

    while True:

        mouse = pygame.mouse.get_pos()

        screen.fill((30,30,30))

        # --------------------------------------------------

        pygame.draw.rect(
            screen,
            (45,45,45),
            (25,25,850,600),
            border_radius=12
        )

        title = title_font.render(
            "Gelbooru Viewer",
            True,
            (255,255,255)
        )

        screen.blit(title,(50,30))

        # ---------------- Tags ----------------

        screen.blit(

            label_font.render("Tags",True,(220,220,220)),

            (60,85)

        )

        pygame.draw.rect(

            screen,

            (90,160,255) if active=="tags" else (120,120,120),

            tag_box,

            2,

            border_radius=6

        )

        tag_surface = text_font.render(
            settings["tags"],
            True,
            (255,255,255)
        )

        screen.blit(tag_surface, (70,129))

        if active == "tags":

            if (pygame.time.get_ticks() // 500) % 2 == 0:

                prefix = settings["tags"][:cursor["tags"]]

                cursor_x = 70 + text_font.size(prefix)[0]

                pygame.draw.line(
                    screen,
                    (255,255,255),
                    (cursor_x,130),
                    (cursor_x,155),
                    2
                )

        # ---------------- Limit ----------------

        screen.blit(

            label_font.render("Max Images (Limit)",True,(220,220,220)),

            (60,185)

        )

        pygame.draw.rect(

            screen,

            (90,160,255) if active=="limit" else (120,120,120),

            limit_box,

            2,

            border_radius=6

        )

        screen.blit(

            text_font.render(settings["limit"],True,(255,255,255)),

            (70,229)

        )

        # ---------------- Checkboxes ----------------

        y = 330

        for key,title in [

            ("randomize","Randomize Order"),

            ("sortscore","Sort by Score"),

        ]:

            box = checkboxes[key]

            pygame.draw.rect(

                screen,

                (220,220,220),

                box,

                2

            )

            if settings[key]:

                pygame.draw.rect(

                    screen,

                    (70,180,255),

                    box.inflate(-6,-6)

                )

            screen.blit(

                label_font.render(title,True,(220,220,220)),

                (95,y-3)

            )

            y += 40

        # ---------------- Start Button ----------------

        colour = (70,150,255)

        if start_button.collidepoint(mouse):

            colour=(90,180,255)

        pygame.draw.rect(

            screen,

            colour,

            start_button,

            border_radius=8

        )

        txt = title_font.render(

            "Start Slideshow",

            True,

            (255,255,255)

        )

        screen.blit(

            txt,

            txt.get_rect(center=start_button.center)

        )

        pygame.display.flip()

        # ==================================================

        for event in pygame.event.get():

            if event.type==pygame.QUIT:

                pygame.quit()

                raise SystemExit

            if event.type==pygame.MOUSEBUTTONDOWN:

                if tag_box.collidepoint(event.pos):

                    active = "tags"

                    rel_x = event.pos[0] - 70

                    cursor["tags"] = len(settings["tags"])

                    for i in range(len(settings["tags"]) + 1):

                        if text_font.size(settings["tags"][:i])[0] >= rel_x:

                            cursor["tags"] = i

                            break

                if limit_box.collidepoint(event.pos):

                    active = "limit"

                    rel_x = event.pos[0] - 70

                    cursor["limit"] = len(settings["limit"])

                    for i in range(len(settings["limit"]) + 1):

                        if text_font.size(settings["limit"][:i])[0] >= rel_x:

                            cursor["limit"] = i

                            break

                elif start_button.collidepoint(event.pos):

                    if settings["tags"]=="":

                        settings["tags"]="landscape"

                    try:

                        settings["limit"]=max(

                            1,

                            int(settings["limit"])

                        )

                    except:

                        settings["limit"]=100

                    return settings

                else:

                    for key,box in checkboxes.items():

                        if box.collidepoint(event.pos):

                            settings[key]=not settings[key]

            if event.type==pygame.KEYDOWN:

                if event.key==pygame.K_ESCAPE:

                    pygame.quit()

                    raise SystemExit

                elif event.key==pygame.K_TAB:

                    active="limit" if active=="tags" else "tags"

                elif event.key==pygame.K_RETURN:

                    if settings["tags"]=="":

                        settings["tags"]="landscape"

                    try:

                        settings["limit"]=max(

                            1,

                            int(settings["limit"])

                        )

                    except:

                        settings["limit"]=100

                    return settings

                elif event.key==pygame.K_BACKSPACE:

                    settings[active]=settings[active][:-1]

                else:

                    text = settings[active]
                    pos = cursor[active]

                    mods = pygame.key.get_mods()

                    # --------------------
                    # Clipboard
                    # --------------------

                    if mods & pygame.KMOD_CTRL:

                        if event.key == pygame.K_v:

                            paste = pyperclip.paste()

                            if active == "limit":

                                paste = "".join(c for c in paste if c.isdigit())

                            text = text[:pos] + paste + text[pos:]

                            cursor[active] += len(paste)

                        elif event.key == pygame.K_c:

                            pyperclip.copy(text)

                        elif event.key == pygame.K_x:

                            pyperclip.copy(text)

                            text = ""

                            cursor[active] = 0

                        elif event.key == pygame.K_a:

                            cursor[active] = len(text)

                    # --------------------
                    # Cursor movement
                    # --------------------

                    elif event.key == pygame.K_LEFT:

                        cursor[active] = max(
                            0,
                            cursor[active]-1
                        )

                    elif event.key == pygame.K_RIGHT:

                        cursor[active] = min(
                            len(text),
                            cursor[active]+1
                        )

                    # --------------------
                    # Delete
                    # --------------------

                    elif event.key == pygame.K_DELETE:

                        if cursor[active] < len(text):

                            text = (

                                text[:cursor[active]]

                                +

                                text[cursor[active]+1:]

                            )

                    # --------------------
                    # Backspace
                    # --------------------

                    elif event.key == pygame.K_BACKSPACE:

                        if cursor[active] > 0:

                            text = (

                                text[:cursor[active]-1]

                                +

                                text[cursor[active]:]

                            )

                            cursor[active] -= 1

                    # --------------------
                    # Typing
                    # --------------------

                    else:

                        if event.unicode.isprintable():

                            if active == "limit":

                                if not event.unicode.isdigit():

                                    settings[active] = text

                                    continue

                            text = (

                                text[:cursor[active]]

                                +

                                event.unicode

                                +

                                text[cursor[active]:]

                            )

                            cursor[active] += 1

                    settings[active] = text

        clock.tick(144)

# ============================================================
# API CLIENT
# ============================================================

class GelbooruClient:

    def __init__(self):

        self.api = "https://gelbooru.com/index.php"

    def latest_posts(self, tag, limit, randomize, sortscore):
        
        if sortscore:
            tag += " sort:score"

        params = {

            "page":"dapi",
            "s":"post",
            "q":"index",
            "json":"1",

            "tags":tag,
            "limit":limit,

            "user_id":USER_ID,
            "api_key":API_KEY,

        }

        print("Requesting latest posts...")

        r = session.get(
            self.api,
            params=params,
            timeout=30
        )

        print(r.url)

        r.raise_for_status()

        data = r.json()

        posts = data.get("post", [])

        good = []

        for post in posts:

            url = post.get("file_url")

            if not url:
                continue

            lower = url.lower()

            if lower.endswith(UNSUPPORTED_EXTENSIONS):
                continue

            if not lower.endswith(SUPPORTED_EXTENSIONS):
                continue

            good.append(post)

        if randomize:
            random.shuffle(good)

        print()

        print(f"Found {len(good)} usable posts.")

        return good

# ============================================================
# IMAGE CACHE
# ============================================================

class ImageCache:

    def __init__(self):

        self.memory = {}

        self.lock = threading.Lock()

    def has(self,url):

        with self.lock:

            return url in self.memory

    def get(self,url):

        with self.lock:

            return self.memory.get(url)

    def put(self,url,image):

        with self.lock:

            self.memory[url]=image

    def disk_name(self,url):

        md5 = hashlib.md5(url.encode()).hexdigest()

        ext = os.path.splitext(url)[1]

        return CACHE_FOLDER / f"{md5}{ext}"

cache = ImageCache()

# ============================================================
# DOWNLOAD IMAGE
# ============================================================

def download_image(url):

    filename = cache.disk_name(url)

    # ------------------------------
    # Already cached on disk
    # ------------------------------

    if filename.exists():

        try:

            img = Image.open(filename)

            img.thumbnail(
                MAX_IMAGE_SIZE,
                Image.Resampling.LANCZOS
            )

            return img.convert("RGB")

        except Exception:

            filename.unlink(missing_ok=True)

    # ------------------------------
    # Download
    # ------------------------------

    r = session.get(
        url,
        timeout=30
    )

    if r.status_code != 200:

        raise RuntimeError(
            f"HTTP {r.status_code}"
        )

    content_type = r.headers.get(
        "Content-Type",
        ""
    )

    if not content_type.startswith("image/"):

        raise RuntimeError(
            f"Server returned {content_type}"
        )

    img = Image.open(
        io.BytesIO(r.content)
    )

    img.thumbnail(
        MAX_IMAGE_SIZE,
        Image.Resampling.LANCZOS
    )

    try:

        img.save(filename)

    except Exception:

        pass

    return img.convert("RGB")

# ============================================================
# CONVERT TO PYGAME
# ============================================================

def pillow_to_surface(img):

    return pygame.image.fromstring(

        img.tobytes(),

        img.size,

        img.mode

    )

# ============================================================
# SCALE TO SCREEN
# ============================================================

def fit_surface(surface,width,height):

    sw = surface.get_width()
    sh = surface.get_height()

    scale = min(

        width/sw,

        height/sh

    )

    nw = int(sw*scale)
    nh = int(sh*scale)

    return pygame.transform.smoothscale(
        surface,
        (nw,nh)
    )

# ============================================================
# PRELOADER
# ============================================================

class Preloader(threading.Thread):

    def __init__(self, posts):

        super().__init__(daemon=True)

        self.posts = posts

        self.running = True

        self.queue = queue.Queue()

        self.failed = set()

        self.total_loaded = 0

        self.current_index = 0

    # --------------------------------------------------------

    def set_index(self, index):

        self.current_index = index

        wanted = []

        for i in range(PRELOAD_COUNT):

            wanted.append(
                (index + i) % len(self.posts)
            )

        queued = set()

        while not self.queue.empty():

            try:
                queued.add(self.queue.get_nowait())
            except queue.Empty:
                break

        for i in wanted:

            if i in queued:
                continue

            self.queue.put(i)

    # --------------------------------------------------------

    def stop(self):

        self.running = False

    # --------------------------------------------------------

    def run(self):

        while self.running:

            try:

                index = self.queue.get(timeout=0.25)

            except queue.Empty:

                continue

            post = self.posts[index]

            url = post["file_url"]

            if url in self.failed:
                continue

            if cache.has(url):
                continue

            try:

                image = download_image(url)

                surface = pillow_to_surface(image)

                cache.put(url, surface)

                self.total_loaded += 1

                print(
                    f"Cached {self.total_loaded}/{len(self.posts)}"
                )

            except Exception as e:

                self.failed.add(url)

                print("Preload skipped:", e)

# ============================================================
# VIEW CACHE ACCESS
# ============================================================

def get_surface(post):

    url = post["file_url"]

    image = cache.get(url)

    if image is not None:
        return image

    try:

        image = pillow_to_surface(
            download_image(url)
        )

        cache.put(url, image)

        return image

    except Exception as e:

        print("Failed:", e)

        return None

# ============================================================
# FADE TRANSITION
# ============================================================

def fade(screen, old, new, speed):

    if old is None:

        screen.fill(BACKGROUND)

        rect = new.get_rect(
            center=screen.get_rect().center
        )

        screen.blit(new, rect)

        pygame.display.flip()

        return

    clock = pygame.time.Clock()

    start = pygame.time.get_ticks()

    while True:

        elapsed = pygame.time.get_ticks() - start

        alpha = min(
            255,
            int(elapsed / speed * 255)
        )

        old.set_alpha(255 - alpha)

        new.set_alpha(alpha)

        screen.fill(BACKGROUND)

        r1 = old.get_rect(
            center=screen.get_rect().center
        )

        r2 = new.get_rect(
            center=screen.get_rect().center
        )

        screen.blit(old, r1)

        screen.blit(new, r2)

        pygame.display.flip()

        if alpha >= 255:
            break

        clock.tick(120)

    old.set_alpha(None)
    new.set_alpha(None)

# ============================================================
# FONT
# ============================================================

pygame.font.init()

overlay_font = pygame.font.SysFont(
    "Consolas",
    22
)

small_font = pygame.font.SysFont(
    "Consolas",
    18
)

# ============================================================
# OVERLAY
# ============================================================

def draw_overlay(

    screen,

    tag,

    index,

    total,

    auto,

    delay,

    preloader,

    fade

):

    if not SHOW_OVERLAY:
        return

    lines = [

        f"Tag: {tag}",

        f"Image: {index+1}/{total}",

        f"Cached: {len(cache.memory)}",

        f"Downloaded: {preloader.total_loaded}",

        f"Auto-scroll: {'ON' if auto else 'OFF'}",

        "R = Toggle Auto-scroll",

        f"Delay: {delay:.2f}s",

        "+/- = Speed",

        f"Fade: {'ON' if fade else 'OFF'}",

        "F = Toggle Fade",

        "TAB = Overlay"
    
    ]

    width = 0

    rendered = []

    for line in lines:

        surf = overlay_font.render(
            line,
            True,
            (255,255,255)
        )

        rendered.append(surf)

        width = max(width, surf.get_width())

    panel = pygame.Surface(
        (
            width + 30,
            len(rendered)*30 + 20
        ),
        pygame.SRCALPHA
    )

    panel.fill((0,0,0,170))

    y = 10

    for surf in rendered:

        panel.blit(
            surf,
            (15,y)
        )

        y += 30

    screen.blit(
        panel,
        (15,15)
    )

# ============================================================
# LOADING SCREEN
# ============================================================

def draw_loading(

    screen,

    text

):

    screen.fill((0,0,0))

    surf = overlay_font.render(
        text,
        True,
        (255,255,255)
    )

    rect = surf.get_rect(
        center=screen.get_rect().center
    )

    screen.blit(
        surf,
        rect
    )

    pygame.display.flip()

# ============================================================
# MAIN APPLICATION
# ============================================================

def main():

    global SHOW_OVERLAY
    global ENABLE_FADE
    global EXCLUDED_TAGS

    pygame.init()

    pygame.display.set_caption(
        "Gelbooru Slideshow Viewer"
    )

    

    # ----------------------------------------
    # Fetch posts
    # ----------------------------------------

    settings = startup_menu()

    tag = settings["tags"] + EXCLUDED_TAGS
    limit = settings["limit"]
    randomize = settings["randomize"]
    sortscore = settings["sortscore"]

    screen = pygame.display.set_mode(
        (0, 0),
        pygame.FULLSCREEN
    )

    screen_width, screen_height = screen.get_size()

    client = GelbooruClient()

    posts = client.latest_posts(
        tag,
        limit,
        randomize,
        sortscore
    )

    if not posts:

        print("No usable posts found.")

        pygame.quit()

        return

    # ----------------------------------------
    # Start preloader
    # ----------------------------------------

    preloader = Preloader(posts)

    preloader.start()

    index = 0

    preloader.set_index(index)

    # ----------------------------------------
    # Wait for first image
    # ----------------------------------------

    draw_loading(
        screen,
        "Loading first image..."
    )

    current = None

    while current is None:

        current = get_surface(
            posts[index]
        )

        if current is None:

            index = (index + 1) % len(posts)

            preloader.set_index(index)

        pygame.time.wait(50)

    current = fit_surface(
        current,
        screen_width,
        screen_height
    )

    clock = pygame.time.Clock()

    running = True

    auto_scroll = False

    auto_delay = AUTO_SCROLL_SECONDS

    last_switch = pygame.time.get_ticks()

    # ----------------------------------------
    # Main loop
    # ----------------------------------------

    while running:

        now = pygame.time.get_ticks()

        # --------------------
        # Auto-scroll
        # --------------------

        if auto_scroll:

            if now - last_switch >= auto_delay * 1000:

                index = (index + 1) % len(posts)

                preloader.set_index(index)

                next_surface = get_surface(
                    posts[index]
                )

                if next_surface:

                    next_surface = fit_surface(
                        next_surface,
                        screen_width,
                        screen_height
                    )

                    if ENABLE_FADE:

                        fade(
                            screen,
                            current,
                            next_surface,
                            FADE_SPEED
                        )

                    current = next_surface

                    last_switch = now

        # --------------------
        # Draw
        # --------------------

        screen.fill(BACKGROUND)

        rect = current.get_rect(
            center=screen.get_rect().center
        )

        screen.blit(
            current,
            rect
        )

        draw_overlay(

            screen,

            tag[:-len(EXCLUDED_TAGS)],

            index,

            len(posts),

            auto_scroll,

            auto_delay,

            preloader,

            ENABLE_FADE

        )

        pygame.display.flip()

        # --------------------
        # Events
        # --------------------

        for event in pygame.event.get():

            if event.type == pygame.QUIT:

                running = False

            elif event.type == pygame.KEYDOWN:

                # ---------------- Quit

                if event.key in (
                    pygame.K_ESCAPE,
                    pygame.K_q
                ):

                    running = False

                # ---------------- Next

                elif event.key in (
                    pygame.K_RIGHT,
                    pygame.K_SPACE
                ):

                    index = (index + 1) % len(posts)

                    preloader.set_index(index)

                    surface = get_surface(
                        posts[index]
                    )

                    if surface:

                        surface = fit_surface(
                            surface,
                            screen_width,
                            screen_height
                        )

                        if ENABLE_FADE:

                            fade(
                                screen,
                                current,
                                surface,
                                FADE_SPEED
                            )

                        current = surface

                        last_switch = pygame.time.get_ticks()

                # ---------------- Previous

                elif event.key == pygame.K_LEFT:

                    index = (index - 1) % len(posts)

                    preloader.set_index(index)

                    surface = get_surface(
                        posts[index]
                    )

                    if surface:

                        surface = fit_surface(
                            surface,
                            screen_width,
                            screen_height
                        )

                        if ENABLE_FADE:

                            fade(
                                screen,
                                current,
                                surface,
                                FADE_SPEED
                            )

                        current = surface

                        last_switch = pygame.time.get_ticks()

                # ---------------- Auto-scroll

                elif event.key == pygame.K_r:

                    auto_scroll = not auto_scroll

                    last_switch = pygame.time.get_ticks()

                    print(
                        "Auto-scroll:",
                        auto_scroll
                    )

                # ---------------- Increase delay

                elif event.key in (
                    pygame.K_EQUALS,
                    pygame.K_PLUS,
                    pygame.K_KP_PLUS
                ):

                    if auto_delay < 0.099:
                        auto_delay += 0.01

                    elif auto_delay < 0.499:
                        auto_delay += 0.05

                    else:
                        auto_delay += 0.1

                    print(
                        auto_delay
                    )

                # ---------------- Decrease delay

                elif event.key in (
                    pygame.K_MINUS,
                    pygame.K_KP_MINUS
                ):
                    
                    if auto_delay < 0.11:
                        auto_delay = max(
                            0.01,
                            auto_delay - 0.01
                        )
                    elif auto_delay < 0.51:
                        auto_delay = max(
                            0.01,
                            auto_delay - 0.05
                        )
                    else:
                        auto_delay = max(
                            0.01,
                            auto_delay - 0.1
                        )

                    print(
                        auto_delay
                    )

                # ---------------- Overlay

                elif event.key == pygame.K_TAB:

                    SHOW_OVERLAY = (
                        not SHOW_OVERLAY
                    )

                # ---------------- Fade

                elif event.key == pygame.K_f:

                    ENABLE_FADE = (
                        not ENABLE_FADE
                    )

        clock.tick(120)

    # ----------------------------------------
    # Shutdown
    # ----------------------------------------

    preloader.stop()

    preloader.join(timeout=2)

    pygame.quit()


# ============================================================
# ENTRY POINT
# ============================================================

if __name__ == "__main__":

    main()
